# Generated by Django 5.1.1 on 2025-04-20 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Business_User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="Components/business_profiles/"
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(default="", null=True)),
                (
                    "user_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_vendor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("whatsapp_link", models.URLField(blank=True, null=True)),
                ("phone", models.CharField(max_length=20)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Carpentry", "Carpentry"),
                            ("Plumbing", "Plumbing"),
                            ("Electrician", "Electrician"),
                            ("Masonry", "Masonry"),
                            ("Salon", "Salon"),
                            ("Medical", "Medical"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("yearofstart", models.CharField(max_length=5)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=2),
                ),
                ("link", models.TextField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("descriptions", models.TextField(blank=True, null=True)),
                ("location", models.CharField(max_length=255)),
                ("lat_long", models.CharField(max_length=25)),
                (
                    "business_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="businesses",
                        to="Businesses.business_user",
                    ),
                ),
            ],
        ),
    ]
