# Generated by Django 5.1.1 on 2024-10-15 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Businesses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='website',
        ),
    ]
