# Generated by Django 5.1.1 on 2025-05-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Businesses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business_user",
            name="is_first_login",
            field=models.BooleanField(default=True),
        ),
    ]
