# Generated by Django 5.1.1 on 2024-11-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Businesses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business_user",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
