# Generated by Django 5.1.1 on 2024-11-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Businesses", "0003_business_user_type_alter_business_user_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business_user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="Components/business_profiles/"
            ),
        ),
    ]
