# Generated by Django 5.1.1 on 2024-11-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlumbingTemp", "0002_alter_plumbing_image_alter_plumbing_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="plumbing",
            name="descriptions",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
