# Generated by Django 5.1.1 on 2024-11-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlumbingTemp", "0003_plumbing_descriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plumbing",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
