# Generated by Django 5.1.1 on 2024-11-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlumbingTemp", "0005_alter_plumbing_descriptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlumbingEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("exact_location", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15)),
                ("query", models.TextField()),
                ("preferred_time", models.DateTimeField()),
                (
                    "email_address",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
            ],
        ),
    ]
