# Generated by Django 5.1.1 on 2024-11-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlumbingTemp", "0006_plumbingenquiry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plumbingenquiry",
            name="preferred_time",
            field=models.CharField(
                choices=[
                    ("Morning", "Morning"),
                    ("Evening", "Evening"),
                    ("Night", "Night"),
                ],
                default="Evening",
                max_length=10,
            ),
        ),
    ]
