# Generated by Django 5.1.1 on 2024-11-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PlumbingTemp", "0008_alter_plumbingenquiry_preferred_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plumbingenquiry",
            name="preferred_time",
            field=models.TextField(max_length=10),
        ),
    ]
