# Generated by Django 5.1.1 on 2024-11-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="category",
            field=models.CharField(
                choices=[
                    ("Carpentry", "Carpentry"),
                    ("Plumbing", "Plumbing"),
                    ("Electrician", "Electrician"),
                    ("Masonry", "Masonry"),
                    ("Salon", "Salon"),
                    ("Medical", "Medical"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.CharField(
                choices=[
                    ("Home-Service", "Home-Service"),
                    ("Shop", "Shop"),
                    ("Item", "Item"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=20,
            ),
        ),
    ]
