# Generated by Django 5.1.1 on 2024-12-29 14:30

import Reviews.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Businesses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.FloatField()),
                (
                    "satisfaction",
                    models.CharField(
                        choices=[
                            ("Very Satisfied", "Very Satisfied"),
                            ("Satisfied", "Satisfied"),
                            ("Neutral", "Neutral"),
                            ("Dissatisfied", "Dissatisfied"),
                            ("Very Dissatisfied", "Very Dissatisfied"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("Very Satisfied", "Very Satisfied"),
                            ("Satisfied", "Satisfied"),
                            ("Neutral", "Neutral"),
                            ("Dissatisfied", "Dissatisfied"),
                            ("Very Dissatisfied", "Very Dissatisfied"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "communication",
                    models.CharField(
                        choices=[
                            ("Very Satisfied", "Very Satisfied"),
                            ("Satisfied", "Satisfied"),
                            ("Neutral", "Neutral"),
                            ("Dissatisfied", "Dissatisfied"),
                            ("Very Dissatisfied", "Very Dissatisfied"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value_for_money",
                    models.CharField(
                        choices=[
                            ("Very Satisfied", "Very Satisfied"),
                            ("Satisfied", "Satisfied"),
                            ("Neutral", "Neutral"),
                            ("Dissatisfied", "Dissatisfied"),
                            ("Very Dissatisfied", "Very Dissatisfied"),
                        ],
                        max_length=20,
                    ),
                ),
                ("review", models.TextField()),
                (
                    "service",
                    models.ForeignKey(
                        default=Reviews.models.get_default_business,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_to_service",
                        to="Businesses.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=Reviews.models.get_default_user,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
