# Generated by Django 5.1.1 on 2024-11-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commonuser",
            name="bookings",
        ),
    ]
