# Generated by Django 5.1.1 on 2024-12-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=15)),
                ("query", models.TextField()),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("Morning", "Morning"),
                            ("Afternoon", "Afternoon"),
                            ("Evening", "Evening"),
                        ],
                        default="Afternoon",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("image", models.ImageField(upload_to="Components/bookingimages/")),
            ],
        ),
    ]
