# Generated by Django 5.1.1 on 2024-12-29 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0002_alter_bookingenquiry_booked_user"),
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingenquiry",
            name="booked_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booked_user",
                to="User.commonuser",
            ),
        ),
    ]
