# Generated by Django 5.1.1 on 2024-11-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0002_booking_bookings"),
        ("User", "0002_remove_commonuser_bookings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="bookings",
        ),
        migrations.AddField(
            model_name="booking",
            name="bookings",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booked_user",
                to="User.commonuser",
            ),
            preserve_default=False,
        ),
    ]
