# Generated by Django 5.1.1 on 2024-12-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0003_alter_bookingenquiry_booked_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingenquiry",
            name="time",
            field=models.CharField(max_length=10),
        ),
    ]
