# Generated by Django 5.1.1 on 2024-11-09 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0004_rename_bookings_booking_booking_user"),
        ("Businesses", "0001_initial"),
        ("Service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offered_by",
                to="Businesses.business_user",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="service_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booked_service",
                to="Service.service",
            ),
        ),
    ]
