# Generated by Django 5.1.1 on 2024-12-29 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0004_alter_bookingenquiry_time"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingenquiry",
            name="booked_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booked_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
