# Generated by Django 5.1.1 on 2024-12-29 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0005_alter_bookingenquiry_booked_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingenquiry",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="Components/bookingimages/"
            ),
        ),
    ]
