# Generated by Django 5.1.1 on 2024-12-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bookings", "0006_alter_bookingenquiry_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingenquiry",
            name="time",
            field=models.TextField(max_length=25),
        ),
    ]
